<p><img alt="banner" height="252px" width="1080px" src="https://docs.google.com/uc?export=download&id=1YJrz-tzQUkofEE37sRUdlCbnXf10gJlF"  align="center" hspace="10px" vspace="0px"></p>

# <font color='056938'> 2.6 -  **Introducción a las** </font> <font color='8EC044'> **estructuras de datos** </font>


---



## <font color='157699'> **Cadenas de caracteres** </font>

Las cadenas de caracteres son estructuras homogéneas, ya que contienen únicamente datos de tipo *string*.



In [ ]:
Nombre = 'Luis Carlos'
Nombre

'Luis Carlos'

In [ ]:
type(Nombre)

str

**Longitud: cantidad de elementos:**

La función `len()` permite determinar la longitud de una cadena de caracteres

In [ ]:
len(Nombre)

11

### <font color='46B8A9'> **Indexación simple:** </font> 

Posición de los elementos dentro de una estructura de datos

### <font color='46B8A9'> **Indexación convencional:** </font>

Inicia en cero (0) para el primer elemento, y va hasta $n-1$, donde $n$ es la cantidad de elementos en la estructura de datos (`len(string)`)

In [ ]:
print('Elemento','Índice', sep='\t')
print('-'*30)
for i in range(len(Nombre)):
    print(Nombre[i], i, sep='\t\t')


Elemento	Índice
------------------------------
L		0
u		1
i		2
s		3
 		4
C		5
a		6
r		7
l		8
o		9
s		10


In [ ]:
Nombre[0]

'L'

In [ ]:
Nombre[7]

'r'

### <font color='46B8A9'> **Indexación inversa:** </font>

En Python se puede hacer indexación comenzando con el último elemento de una estructura de datos, el cual tendrá el índice -1. Los elementos atrás de éste disminuyen su índice en -1 por cada posición:

In [ ]:
n = len(Nombre)
print('Elemento\t','Índice convencional\t', 'Índice invertido', sep='')
print('-'*56)
for i in range(len(Nombre)):
    print(Nombre[i], i, i-n, sep='\t\t\t')

Elemento	Índice convencional	Índice invertido
--------------------------------------------------------
L			0			-11
u			1			-10
i			2			-9
s			3			-8
 			4			-7
C			5			-6
a			6			-5
r			7			-4
l			8			-3
o			9			-2
s			10			-1


In [ ]:
Nombre[-1]

's'

In [ ]:
Nombre[-5]

'a'

In [ ]:
Nombre[-10]

'u'

El primer elemento de cualquier estructura se puede hallar usando indexación inversa y la longitud de ésta:

In [ ]:
Nombre[-n]

'L'

### <font color='46B8A9'> **Indexación por grupos (*slicing*):** </font>

En Python es posible acceder a una porción continua de elementos en una estructura de datos, usando indexación por grupos. Esta forma de indexar, también permite acceder a elementos específicos no contiguos.

El último índice del grupo no se incluye, sólo se incluye desde el primero ante el anterior al último indicado: <br>
`[i:j]` incluirá desde el índice `i` hasta el índice `j-1`.

In [ ]:
Nombre[0:4]

'Luis'

En la unidad 4 se dan más detalles sobre la indexación de estructuras de datos.

#### <font color='#00B0F0'> **Ejercicio 1** </font>

Considere la siguiente cadena de texto "Hola, este es mi primera práctica con la indexación"

Obtenga el primer caracter de la cadena de texto:

In [ ]:
# Ingrese aquí su respuesta


Obtenga los tres últimos caracteres de la cadena de texto

In [ ]:
# Ingrese aquí su respuesta


Obtenga los caracteres entre las posiciones 9 y 18 del texto

In [ ]:
# Ingrese aquí su respuesta


## <font color='157699'> **Arreglos** </font>

Los arreglos son estructuras homogéneas, ya que sólo contienen datos de tipo numérico. Éstos pueden ser de una o más dimensiones, y en Python se crean y se usan mediante la librería Numpy, sobre la cual se tratará en la unidad 4.

### <font color='46B8A9'> **Arreglos unidimensionales:** vectores </font>
Se tienen datos organizados en forma de lista

In [ ]:
import numpy as np
X = np.array([14, 12, 8, 7, 6.41, 5.23, 6.15, 7.25])
X

array([14.  , 12.  ,  8.  ,  7.  ,  6.41,  5.23,  6.15,  7.25])

In [ ]:
type(X)

numpy.ndarray

La indexación para arreglos unidemiensionales es igual que para las cadenas de caracteres

In [ ]:
X[0]

14.0

In [ ]:
X[-1]

7.25

In [ ]:
len(X)

8

In [ ]:
X[2:6]

array([8.  , 7.  , 6.41, 5.23])

In [ ]:
len(X)

8

En la unidad 4 se verá en detalle la creación y manipulación de arreglos

### <font color='46B8A9'> **Arreglos bidimensionales:** matrices </font>

En este caso los datos numéricos están organizados tipo tabla, y se usan dos dimensiones, conocidas como filas (horizontales) y columnas (verticales).

In [ ]:
Matriz_1 = np.array([[23,78,100],[67,99,45],[1,74,325],[22,10,20]])
Matriz_1

array([[ 23,  78, 100],
       [ 67,  99,  45],
       [  1,  74, 325],
       [ 22,  10,  20]])

La indexación en arreglos bidimensionales se realiza usando dos índices: en primer lugar se indica la fila (`i`), y en segundo lugar la columna (`j`).

In [ ]:
Matriz_1[0,1]

78

In [ ]:
Matriz_1[2,2]

325

De nuevo, se puede usar indexación inversa:

In [ ]:
Matriz_1[-1,-2]

10

### <font color='46B8A9'> **Arreglos tridimensionales:** hipermatrices </font>

In [ ]:
HM = np.array([[[1, 2],[3, 5]],[[4, 9],[6, -4]],[[0, 7],[14, 35]]])
HM

array([[[ 1,  2],
        [ 3,  5]],

       [[ 4,  9],
        [ 6, -4]],

       [[ 0,  7],
        [14, 35]]])

Si se indica un único índice, éste se refiere a la matriz dentro de la hipermatriz:

In [ ]:
HM[1]

array([[ 4,  9],
       [ 6, -4]])

En este caso se requieren tres indices para indexar un elemento en el arreglo: primero la matriz (`k`), luego la fila (`i`), y finalmente la columna (`j`).

In [ ]:
HM[1,1,1]

-4

In [ ]:
HM[-1,-1,-1]

35

In [ ]:
HM[-1,0,0]

0

#### <font color='#00B0F0'> **Ejercicio 2** </font>

Considere la hipermatriz de tres dimensiones, 

> `HM = np.array([[[1, 2],[3, 5]],[[4, 9],[6, -4]],[[0, 7],[14, 35]]])`

Intente imaginarla como un cubo y obtenga los valores que estarían en cada una de las 8 esquinas del cubo



In [ ]:
# Inserte aquí su respuesta


## <font color='157699'> **Registros:** Estructuras heterogéneas </font>

Este tipo de estructuras pueden contener datos de diferentes tipos: cadenas de caracteres, numéricos, lógicos, etc. Incluso es posible anidar unas estructuras de datos dentro otras.

En Python las estructuras de datos más comunes de este tipo son las listas, tuplas y diccionarios.

### <font color='46B8A9'> **Listas** </font>

Son estructuras unidimensionales, mutables (se puede cambiar el valor de sus elementos de forma independiente), y permiten anidar otras estructuras de datos. En la unidad 4 se verá en detalle la creación y manipulación de este tipo de estructuras.

In [ ]:
# Se crean usando corchetes [ ]
lista_1 = [14, 'Carlos Mario', Matriz_1, X]
lista_1

[14, 'Carlos Mario', array([[ 23,  78, 100],
        [ 67,  99,  45],
        [  1,  74, 325],
        [ 22,  10,  20]]), array([14.  , 12.  ,  8.  ,  7.  ,  6.41,  5.23,  6.15,  7.25])]

In [ ]:
lista_1[0]

14

In [ ]:
lista_1[1]

'Carlos Mario'

En la indexación, cuando no se escribe después de los dos puntos (`:`), se incluyen los elementos de la estructura de datos hasta el final de ésta:

In [ ]:
lista_1[1][-5:]

'Mario'

In [ ]:
lista_1[2]

array([[ 23,  78, 100],
       [ 67,  99,  45],
       [  1,  74, 325],
       [ 22,  10,  20]])

In [ ]:
lista_1[2][1,:]

array([67, 99, 45])

In [ ]:
lista_1[3]

array([14.  , 12.  ,  8.  ,  7.  ,  6.41,  5.23,  6.15,  7.25])

In [ ]:
lista_1[3][::-1]

array([ 7.25,  6.15,  5.23,  6.41,  7.  ,  8.  , 12.  , 14.  ])

In [ ]:
lista_1[0] = [1, 2, 3]
lista_1

[[1, 2, 3], 'Carlos Mario', array([[ 23,  78, 100],
        [ 67,  99,  45],
        [  1,  74, 325],
        [ 22,  10,  20]]), array([14.  , 12.  ,  8.  ,  7.  ,  6.41,  5.23,  6.15,  7.25])]

### <font color='46B8A9'> **Tuplas** </font>
Son similares a las listas, excepto que son inmutables, es decir, que no se permite modificar sus elementos:

In [ ]:
# Se deben crear usando paréntesis
tupla_1 = (14, 'Carlos Mario', Matriz_1, X)
tupla_1

(14, 'Carlos Mario', array([[ 23,  78, 100],
        [ 67,  99,  45],
        [  1,  74, 325],
        [ 22,  10,  20]]), array([14.  , 12.  ,  8.  ,  7.  ,  6.41,  5.23,  6.15,  7.25]))

In [ ]:
tupla_1[0]

14

In [ ]:
tupla_1[2]

array([[ 23,  78, 100],
       [ 67,  99,  45],
       [  1,  74, 325],
       [ 22,  10,  20]])

In [ ]:
#Las tuplas son inmutables, por lo tanto, la siguiente linea no deberia ejecutar.
tupla_1[0] = 5

### <font color='46B8A9'> **Diccionarios** </font>

Son una estructura similar a las listas, pero sin un orden dado por índices. En este caso cada elemento consta de dos partes: `clave:valor`, donde la clave es un identificador, que hace las veces de índice, pero que puede ser una variable de tipo numérico o de otro tipo, y el valor puede ser también de cualquier tipo de dato. Se crean usando llaves: `{ }`.

In [ ]:
dicc_1 = {'Nombre':'Pedro', 'Apellido':'Jiménez', 'Identificación':123456789, 'Edad':21, 127:'Clave numérica'}
dicc_1

{'Nombre': 'Pedro',
 'Apellido': 'Jiménez',
 'Identificación': 123456789,
 'Edad': 21,
 127: 'Clave numérica'}

In [ ]:
dicc_1['Nombre']

'Pedro'

In [ ]:
dicc_1['Identificación']

123456789

In [ ]:
dicc_1['Apellido']

'Jiménez'

In [ ]:
dicc_1[127]

'Clave numérica'

En esta última celda se evidencia la diferencia con las otras estructuras de datos, ya que 127 no es un índice, sino la clave, cuyo valor es la cadena de caracteres "Clave numérica"

In [ ]:
len(dicc_1)

5

## <font color='157699'> **Ejercicios** </font>

#### <font color='#00B0F0'> **Ejercicio 3** </font>

Cree una lista con todas las asignaturas que esta cursando este semestre

In [ ]:
# Inserte su respuesta aquí

#### <font color='#00B0F0'> **Ejercicio 4** </font>

Para las asignaturas que cursa este semestre, cree una lista de tuplas, donde cada tuplas es el nombre de la asignatura y los créditos que le corresponden

In [ ]:
# Inserte su código aquí

#### <font color='#00B0F0'> **Ejercicio 5** </font>

Para las asignaturas que cursa este semestre, cree un diccionario, donde las claves son los códigos de la asignatura que esta cursando y el valor es el nombre de la asignatura

In [ ]:
# Inserte su código aquí